pipelines:
  pull-requests:
    '**':
      - step:
          image: python:3.7-alpine3.9
          services:
            - docker
          script:
            - pip install -q -r requirements.txt
            - py.test tests/