image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Build/test/push release-maker image
          services:
            - docker
          script:
            - echo ${DOCKER_BOT_PASSWORD} | docker login docker-public.packages.atlassian.com --username ${DOCKER_BOT_USERNAME} --password-stdin
            - docker build -t docker-public.packages.atlassian.com/atlassian/docker-release-maker:latest .
            - docker push docker-public.packages.atlassian.com/atlassian/docker-release-maker:latest

            - nvm install 14.16 # Snyk needs a newer version
            - npm install snyk
            - npx snyk auth $SNYK_TOKEN
            - npx snyk container test docker-public.packages.atlassian.com/atlassian/docker-release-maker:latest --severity-threshold=high
            - npx snyk container monitor docker-public.packages.atlassian.com/atlassian/docker-release-maker:latest --severity-threshold=high

    '**':
      - step:
          name: Build/test release-maker image
          services:
            - docker
          script:
            - curl -sL https://github.com/hadolint/hadolint/releases/download/v2.1.0/hadolint-Linux-x86_64 -o ./hadolint
            - chmod +x ./hadolint
            - ./hadolint Dockerfile

            - docker build -t docker-release-maker:local .
            - docker run -e DOCKER_BOT_USERNAME -e DOCKER_BOT_PASSWORD  --rm docker-release-maker:local py.test

            - nvm install 14.16 # Snyk needs a newer version
            - npm install snyk
            - npx snyk auth $SNYK_TOKEN
            - npx snyk container test docker-release-maker:local --severity-threshold=high
