image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Build/test/push release-maker image
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - docker build -t atlassian/docker-release-maker:latest .

            - nvm install node # Snyk needs a newer version
            - npm install -g snyk
            - snyk auth $SNYK_TOKEN
            - snyk container test atlassian/docker-release-maker:latest --severity-threshold=high

            - docker push atlassian/docker-release-maker:latest
            - snyk container monitor atlassian/docker-release-maker:latest --severity-threshold=high

    '**':
      - step:
          name: Build/test release-maker image
          services:
            - docker
          script:
            - docker build -t "drm:dev" .
            - docker run --rm drm:dev py.test

            - docker build -t atlassian/docker-release-maker:localtest .

            - nvm install node # Snyk needs a newer version
            - npm install -g snyk
            - snyk auth $SNYK_TOKEN
            - snyk container test atlassian/docker-release-maker:localtest --severity-threshold=high
