image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Build/test/push release-maker image
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - docker build -t atlassian/docker-release-maker:latest .

            - nvm install 14.16 # Snyk needs a newer version
            - npm install snyk
            - npx snyk auth $SNYK_TOKEN
            - npx snyk container test atlassian/docker-release-maker:latest --severity-threshold=high

            - docker push atlassian/docker-release-maker:latest
            - snyk container monitor atlassian/docker-release-maker:latest --severity-threshold=high

    '**':
      - step:
          name: Build/test release-maker image
          services:
            - docker
          script:
            - docker build -t docker-release-maker:local .
            - docker run --rm docker-release-maker:local py.test

            - nvm install 14.16 # Snyk needs a newer version
            - npm install snyk
            - npx snyk auth $SNYK_TOKEN
            - npx snyk container test docker-release-maker:local --severity-threshold=high
